version: '3'
services:
  nginx:
    image: nginx
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  odoo:
    image: odoo:latest
    depends_on:
      - db
    volumes:
      - odoo11-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo11-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo11-web-data:
  odoo11-db-data:
